# Gulp will reference these paths when it copies files
PATHS:
  html:
    - "./*.html"
    - "./**/*.html"
  images:
    src:
      - "assets/img/src/**/*"
    dest:
      - "assets/img"
  css:
    - "assets/css"
  sass:
    - "assets/scss/**/*.scss"
  js:
    src:
      - "node_modules/typeit/dist/index.umd.js"
      - "assets/js/src/**/*.js"
    dest:
      - "assets/js"
